server:  
  port: 8090  
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8  
spring:
  mvc :
    view :
      prefix : /WEB-INF/jsp/
      suffix : .jsp
  datasource:  
    url : jdbc:mysql://127.0.0.1:3306/happy_live?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username : root  
    password : 123456  
    driverClassName : com.mysql.cj.jdbc.Driver
  jpa:  
    database : MYSQL  
    show-sql : true  
    hibernate:  
      ddl-auto : update  
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy  
    properties:  
      hibernate:  
        dialect : org.hibernate.dialect.MySQL5Dialect 